name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up SSH and add EC2 host key
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        echo -e "Host ec2-instance\n\tHostName ${{ secrets.EC2_HOST }}\n\tUser ${{ secrets.EC2_USER }}\n\tIdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config

    # Step 3: Create target directory on EC2
    - name: Ensure target directory exists
      run: |
        ssh ec2-instance "mkdir -p /home/${{ secrets.EC2_USER }}/app"

    # Step 4: Copy files to EC2
    - name: Copy files to EC2
      run: |
        scp -r ./* ec2-instance:/home/${{ secrets.EC2_USER }}/app

    # Step 5: Run deployment script on EC2
    - name: Execute deployment script
      run: |
        ssh ec2-instance "cd /home/${{ secrets.EC2_USER }}/app && ./deploy.sh"
        